2020-10-26 11:47:46,367 INFO    MainThread:16228 [wandb_init.py:_log_setup():293] Logging user logs to wandb\run-20201026_114746-19pdwvgq\logs\debug.log
2020-10-26 11:47:46,367 INFO    MainThread:16228 [wandb_init.py:_log_setup():294] Logging internal logs to wandb\run-20201026_114746-19pdwvgq\logs\debug-internal.log
2020-10-26 11:47:46,367 INFO    MainThread:16228 [wandb_setup.py:_flush():69] setting env: {}
2020-10-26 11:47:46,367 INFO    MainThread:16228 [wandb_setup.py:_flush():69] setting user settings: {'email': 'leshhuk3@gmail.com'}
2020-10-26 11:47:46,367 INFO    MainThread:16228 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn
2020-10-26 11:47:48,062 INFO    MainThread:16228 [wandb_run.py:_console_start():1290] atexit reg
2020-10-26 11:47:48,063 INFO    MainThread:16228 [wandb_run.py:_redirect():1160] redirect: SettingsConsole.WRAP
2020-10-26 11:47:48,063 INFO    MainThread:16228 [wandb_run.py:_redirect():1191] Wrapping output streams.
2020-10-26 11:47:48,063 INFO    MainThread:16228 [wandb_run.py:_redirect():1207] Redirects installed.
2020-10-26 11:47:48,063 INFO    MainThread:16228 [wandb_config.py:__setitem__():64] config set i = binary:logistic - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000191471ED3A0>>
2020-10-26 11:47:48,063 INFO    MainThread:16228 [wandb_run.py:_config_callback():591] config_cb i binary:logistic {'_wandb': {'cli_version': '0.10.8', 'python_version': '3.8.5', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'lightgbm'}, 'i': 'binary:logistic'}
2020-10-26 11:47:48,068 INFO    MainThread:16228 [wandb_run.py:_atexit_cleanup():1263] got exitcode: 1
2020-10-26 11:47:48,068 INFO    MainThread:16228 [wandb_run.py:_restore():1235] restore
2020-10-26 11:47:49,036 INFO    MainThread:16228 [wandb_run.py:_wait_for_finish():1377] got exit ret: uuid: "eaf211723fd44e99a12b4cf0380fea4b"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 773
      total_bytes: 773
    }
  }
}

2020-10-26 11:47:51,056 INFO    MainThread:16228 [wandb_run.py:_wait_for_finish():1377] got exit ret: uuid: "6fb89ca771c54729a4638f02e9f0efb6"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8708
      total_bytes: 8708
    }
  }
}

2020-10-26 11:47:52,152 INFO    MainThread:16228 [wandb_run.py:_show_files():1586] logging synced files
2020-10-26 11:47:52,153 INFO    MainThread:16228 [internal.py:handle_exit():137] Internal process exited
