2020-10-26 11:54:04,781 INFO    MainThread:16196 [internal.py:wandb_internal():62] W&B internal server running at pid: 16196
2020-10-26 11:54:04,782 INFO    WriterThread:16196 [datastore.py:open_for_write():76] open: wandb\run-20201026_115403-1vhvddtp\run-1vhvddtp.wandb
2020-10-26 11:54:04,783 DEBUG   HandlerThread:16196 [handler.py:handle_request():54] handle_request: check_version
2020-10-26 11:54:04,784 DEBUG   SenderThread:16196 [sender.py:send():89] send: header
2020-10-26 11:54:04,784 DEBUG   SenderThread:16196 [sender.py:send():89] send: request
2020-10-26 11:54:04,784 DEBUG   SenderThread:16196 [sender.py:send_request():98] send_request: check_version
2020-10-26 11:54:04,791 DEBUG   Thread-8  :16196 [connectionpool.py:_new_conn():812] Starting new HTTPS connection (1): pypi.org:443
2020-10-26 11:54:04,872 DEBUG   Thread-8  :16196 [connectionpool.py:_make_request():391] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51107
2020-10-26 11:54:04,936 DEBUG   SenderThread:16196 [sender.py:send():89] send: run
2020-10-26 11:54:04,951 DEBUG   SenderThread:16196 [util.py:is_cygwin_git():314] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
2020-10-26 11:54:04,953 DEBUG   SenderThread:16196 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Python\Colgate\brush_paste, universal_newlines=False, shell=None, istream=<valid stream>)
2020-10-26 11:54:04,988 DEBUG   SenderThread:16196 [connectionpool.py:_new_conn():812] Starting new HTTPS connection (1): api.wandb.ai:443
2020-10-26 11:54:05,202 DEBUG   SenderThread:16196 [connectionpool.py:_make_request():391] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-10-26 11:54:05,268 DEBUG   HandlerThread:16196 [handler.py:handle_request():54] handle_request: run_start
2020-10-26 11:54:05,271 INFO    SenderThread:16196 [dir_watcher.py:__init__():167] watching files in: wandb\run-20201026_115403-1vhvddtp\files
2020-10-26 11:54:05,271 INFO    SenderThread:16196 [sender.py:_start_run_threads():486] run started: 1vhvddtp with start time 1603702443
2020-10-26 11:54:05,271 DEBUG   SenderThread:16196 [sender.py:send():89] send: summary
2020-10-26 11:54:05,272 INFO    SenderThread:16196 [sender.py:_save_file():567] saving file wandb-summary.json with policy end
2020-10-26 11:54:05,294 DEBUG   HandlerThread:16196 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Python\Colgate\brush_paste, universal_newlines=False, shell=None, istream=<valid stream>)
2020-10-26 11:54:05,327 DEBUG   HandlerThread:16196 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=C:\Python\Colgate\brush_paste, universal_newlines=False, shell=None, istream=None)
2020-10-26 11:54:05,468 DEBUG   HandlerThread:16196 [handler.py:handle_request():54] handle_request: status
2020-10-26 11:54:05,470 DEBUG   SenderThread:16196 [sender.py:send():89] send: files
2020-10-26 11:54:05,470 INFO    SenderThread:16196 [sender.py:_save_file():567] saving file wandb-metadata.json with policy now
2020-10-26 11:54:05,477 DEBUG   HandlerThread:16196 [handler.py:handle_request():54] handle_request: poll_exit
2020-10-26 11:54:05,479 DEBUG   SenderThread:16196 [sender.py:send():89] send: request
2020-10-26 11:54:05,479 DEBUG   SenderThread:16196 [sender.py:send_request():98] send_request: status
2020-10-26 11:54:05,480 DEBUG   SenderThread:16196 [connectionpool.py:_new_conn():812] Starting new HTTPS connection (1): api.wandb.ai:443
2020-10-26 11:54:05,487 DEBUG   Thread-17 :16196 [connectionpool.py:_new_conn():812] Starting new HTTPS connection (1): api.wandb.ai:443
